server:
  port: 8080
spring:
  application:
    name: "personcustomer"
  devtools:
    add-properties: false
    livereload:
      enabled: off
    restart:
      enabled: off
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: /
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}   # o el nombre del servicio docker-compose
    port: ${DB_PORT:5436}
    database: ${DB_NAME:postgres}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
